version: '3.8'

services:
  order-service:
    image: order-service
    build:
      context: ./order
    ports:
      - "8085:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_order:3306/order
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=group_id
    depends_on:
      - db_order
    networks:
      - my-network

  product-service:
    image: product-service
    build:
      context: ./product
    ports:
      - "8086:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_product:3306/product_order
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db_product
    networks:
      - my-network

  db_order:
    image: mysql:8
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user           # Custom user
      MYSQL_PASSWORD: user # Password for custom user
    ports:
      - "3307:3306"
    volumes:
      - db_order_data:/var/lib/mysql  # Persist database data
    networks:
      - my-network

  db_product:
    image: mysql:8
    environment:
      MYSQL_DATABASE: product_order
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user           # Custom user
      MYSQL_PASSWORD: user # Password for custom user
    ports:
      - "3308:3306"
    volumes:
      - db_product_data:/var/lib/mysql  # Persist database data
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_order_data:
  db_product_data: